### PR TITLE
GB - United Kingdom - Latest revision of ISO 3166:GB (2022-03-03)

### PR DESCRIPTION
**Pull request by miles-cloudlead**
As per https://www.iso.org/obp/ui/#iso:code:3166:GB

Tests passing...

image

### CODE REVIEW

**Comment by benkeen** [comment]
Thanks @miles-cloudlead!

**Comment by miles-cloudlead** [comment]
> Thanks @miles-cloudlead!

No worries @benkeen , my pleasure! 👍

**Comment by miles-cloudlead** [comment]
@benkeen do you mind me asking when this might make it to npm?

**Comment by benkeen** [comment]
Ah sorry @miles-cloudlead - will release a fresh version tonight.

**Comment by miles-cloudlead** [comment]
> Ah sorry @miles-cloudlead - will release a fresh version tonight.

Awesome, thanks @benkeen !

**Pull request merged**
