### PR TITLE
Update Vietnam Regions

### LINKED ISSUE #85: Vietnam missing regions
There seem to be missing a few regions for ISO-3166 Vietnam regions.
https://www.iso.org/obp/ui/#iso:code:3166:VN

### PR DESCRIPTION
**Pull request by barnett**
Added a few missing regions using this definition: https://www.iso.org/obp/ui/#iso:code:3166:VN

### CODE REVIEW

**Comment by barnett** [comment]
@benkeen thanks for the review and merge! 

To help our planning, when do you expect the release to be available?

**Comment by benkeen** [comment]
Oh sure - I'll release a new version tonight. Thanks!

**Comment by benkeen** [comment]
Updated. You can now download `country-region-data@1.11.0`. 

Thanks again.

**Comment by barnett** [comment]
Thank you so much! We appreciate it.

**Pull request merged**
