### PR TITLE
Add Romania Capitol Bucharest

### PR DESCRIPTION
**Pull request by yukosgiti**
PS: I made up the shortCode.

### CODE REVIEW

**Comment by benkeen** [comment]
Thanks @yukosgiti, sorry for the long response time! Looks like the short codes weren't quite correct - they should be ISO-3166-2, so `RO-B` for this one. If you're too busy, no worries I'll get it updated and merged in the next few days.

**Comment by ElenaIf** [comment]
Hi, @benkeen and @yukosgiti, are you planning to update and merge this some time soon? Thank you in advance.

**Comment by benkeen** [comment]
Sure, no problem. Let me take a look. 

Were you using this library separately or with react-country-region-selector or another? Wondering if I'll need to update those as well for the new country-region-data version.

**Comment by benkeen** [comment]
I'll merge this and make the change separately.

**Comment by benkeen** [comment]
This has been published in `country-region-data@2.7.0`.

**Comment by ElenaIf** [comment]
Thanks for updating! I use raw data.json

**Pull request merged**
